#tells spring where to locate the config files
#spring.cloud.config.server.native.search-locations= classpath:/configs

#we are using native because the config server uses a git repo by default
#spring.profiles.active= native

#the password which apps will use to access its configurations
#spring.security.user.password=1234

#the port where the config-server will be accessible.
#server.port=8899
server:
  port: 8899
spring:
  application:
    name: configservice
  security:
    user:
      password: 1234
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
        git:
          uri: classpath:/configs